import subprocess
import os

# Step 1: Define the code to be written to the new Python file.
code = """
print("Hello, World!")
print("This script was generated by another Python script.")
"""

# Step 2: Define the directory and file name.
directory = os.path.expandvars(r'%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup') #add to shell:startup
file_name = os.path.join(directory, "harmless_script.py")

# Ensure the directory exists
os.makedirs(directory, exist_ok=True)

# Step 3: Open a new file in write mode.
with open(file_name, "w") as file:
    # Step 4: Write the defined code to the file.
    file.write(code)


# Step 6: Use the subprocess module to run the newly created Python file.
subprocess.run(["python", file_name])